[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
base="light"
primaryColor="#0B5FFF"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F6F8FB"
textColor="#111827"
font="sans serif"
